screens/Home.js
This PR fixes a warning, which was displayed on the home screen.
=> Fix "key prop" warning in Home screen.

components/homeRouter.js, screens/Home.js
=> Fix incorrect merge after conflict resolution

components/WorkoutCard.js
Small fix to show border shadow on android devices
=> Fix shadow on Android devices

components/homeRouter.js
=> added bottom tab bar navigation

lib/auth/index.js, screens/Settings.js
=> Implement delete account functionality.

components/ExerciseCard.js, components/homeRouter.js, screens/CreateWorkout.js, screens/Home.js, screens/WorkoutDetails.js
=> Implement CreateWorkout screen

screens/Home.js, screens/RunWorkout/RunWorkoutScreen.js, screens/RunWorkout/Timer.js, screens/RunWorkout/TimerView.js
Added Pause, Resume & switch current timer  functionality to Run workout screen. 
video is at 1.5x speed
=> Run workout

components/ExerciseCard.js, components/SetCard.js, screens/CreateWorkout.js
This PR contains implementation of sets functionality in the `CreateWorkout` component.
Now, it adds, and updates sets properly. Also, there are a few small features in this PR:
- "Save" button was moved to the navigation bar.
- I added "saved" state to the `CreateWorkout` component. So, if user wants to go back, and the workout wasn't saved, an alert would pop up.
=> Add sets functionality to CreateWorkout

screens/Discover.js
This is similar to Home screen, it checks if status has changed (darkTheme for now) when returned to the screen
=> Small fix - adds an observer to watch change of Theme property 

android/app/src/main/java/com/myfitnessgoapp/fitnessgo/MainApplication.java, ios/FitnessGo/AppDelegate.m
Offline mode for FB database. 
**No internet before**
<hr/>
**No internet now**
=> Added percistence (offline) to firebase database

screens/Home.js
=> Connect Firebase: read user's workouts from firebase and display them on Home screen

screens/CreateWorkout.js
This PR adds some workout categories, feel free to drop some more 👇
=> Add more workout categories

screens/CreateWorkout.js
A little adjustment in how new workouts are saved: 
1) generate a new db ref (generates a key)
2) set workout id to be the same as the ref key
3) update db ref with the new workout object
=> Use database unique key as a workout id

App.js, package-lock.json, package.json, screens/WorkoutDetails.js
Added Info messages capability.
Notify user about successful or failed events. 
Show messages on any screen with: 
1) import showMessage comp.
`import { showMessage } from "react-native-flash-message";`
2) Show message when needed
`showMessage({message: "Simple message", type: "info",});`
[API reference](https://www.npmjs.com/package/react-native-flash-message)
=> Added info messages

components/DiscoverItem.js, screens/Discover.js
**Added menu actions:** 
- Play workout 
- Details
- Add workout to user lib
**Added label created by**
**Added button to play workout**
**Added label when workout added to user library**
=> Discover screen workout card adjustment

components/DiscoverItem.js, screens/Discover.js
=> Fix pop up menu not opening on long press

components/ExerciseCard.js, components/SetCard.js, screens/CreateWorkout.js
=> CreateWorkout: add delete exercises/sets functionality

screens/Discover.js, screens/Home.js
Pull to refresh for Home and Discover screens. 
Fetches workouts from the database on user request
.
=> Add pull to refresh

components/WorkoutInfoView.js, screens/Home.js
=> Home screen: implement delete workout functionality

App.js, screens/Discover.js, screens/Home.js
Adjusted Discover screen:
- If the workout from discover was already added, the proper message will be show.
- When workout added to the user library the message is displayed and a label "Added to your library"  will now appear on a Workout card .
- Added additional check onRefresh event. If the user has deleted a workout from the user library then the label "Added to your library" will be removed accordingly.
Also fixed:
- Moved MenuProvider to the top level to remove error _"in most cases you should not have more menu providers in your app (see API documentation). In other cases use skipinstacecheck prop"_
=> Adjust adding to user lib

components/ExerciseCard.js, screens/CreateWorkout.js
Low battery notification is not part of this PR 🙂
=> Fetch predefined exercices from firebase

components/ExerciseCard.js, components/SetCard.js, components/homeRouter.js, screens/CreateWorkout.js
=> Add CreateWorkout screen adjustments

components/homeRouter.js, screens/Discover.js
=> added settings icon to discover screen

components/DatabaseManager.js, screens/Discover.js, screens/Home.js, screens/WorkoutDetails.js, styles/global.js
Added share workout functionality:
Share workout from Discover or Home screen generates the code that the user can send to any number of people. 
To open shared workout the user long presses a + button on home screen and enters a code they received. (#61)
To add that workout to their library user clicks Add button in the Nav bar
=> Share workout

components/ExerciseCard.js, components/SetCard.js, screens/EditWorkout.js, screens/ExerciseDetailsView.js, screens/Home.js, screens/WorkoutDetails.js
=> Implement edit workout functionality

screens/RunWorkout/RunWorkoutScreen.js
Replaced alert with new overlay screen
=> Run workout: completion overlay view

screens/ExerciseDetailsView.js
=> Add images to details screen

components/ExerciseCard.js, screens/ExerciseDetailsView.js
=> Create/Edit workout: add images

components/SetCard.js, screens/SetDetailsView.js
=> Add weight field to sets

screens/CreateAccount.js, screens/CreateWorkout.js, screens/Discover.js, screens/EditWorkout.js, screens/Home.js, screens/LogInOptions.js, screens/RunWorkout/RunWorkoutScreen.js, screens/Settings.js, screens/Start.js, screens/WorkoutDetails.js
For #60
- bottom bar remains unchanged, so put (beta) next to the dark mode switch
=> Global dark theme switch

components/homeRouter.js
Added prop for tab bar to hide default tab names
=> Hide tab lables (default names)

components/homeRouter.js, screens/About.js, screens/Settings.js
Added About screen with references to used images and sounds
=> About screen with asset references

components/DatabaseManager.js, screens/Settings.js
User data will now be removed when they delete their account
=> Delete user data on delete account

screens/RunWorkout/RunWorkoutScreen.js, screens/RunWorkout/Timer.js, screens/RunWorkout/TimerView.js
Weight is now displayed on Run Workout screen for sets that have weight specified
=> Added weight field for Run workout screen

screens/Home.js
Made wrapper view around Add button that blocked a good chunk of a screen transparent
=> Made Add button wrapper view transparent

android/app/src/main/AndroidManifest.xml, components/ExerciseCard.js, components/SetCard.js, components/WorkoutCard.js, screens/CreateWorkout.js, screens/Discover.js, screens/Home.js
Fixes:
- Fixed Button background color on android on Create Workout screen
- Fixed Alignment of "Add set" button on Android
- Fixed views being squished to the top of the screen when keyboard opens on Android
- Fixed truncation of exercise description field when it was too long
**Before:** 
<hr/>
**After:**
Adjustments: 
- Created by is only shown for workouts added by someone else
=> Android adjustments

android/app/src/main/java/com/myfitnessgoapp/fitnessgo/MainApplication.java, ios/FitnessGo.xcodeproj/project.pbxproj, ios/FitnessGo/Info.plist, ios/Podfile, lib/auth/index.js, package-lock.json, package.json, screens/LogInOptions.js
Removed NetInfo and @react net info that caused android crash in release
=> Removed NetInfo
